# Generated by Django 2.0.5 on 2019-08-09 18:06

from django.db import migrations, models
import djongo.models.fields
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('birthdate', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('department', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('primary_mobile', models.CharField(max_length=10)),
                ('secondary_mobile', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('birthdate', models.DateField()),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diploma_12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('placed', models.BooleanField(default=False)),
                ('primary_mobile', models.CharField(max_length=10)),
                ('secondary_mobile', models.CharField(blank=True, max_length=10)),
                ('attendence_status', models.BooleanField(default=False)),
                ('marks', djongo.models.fields.ArrayModelField(model_container=registration.models.Year_marks)),
                ('avg_marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
