# Generated by Django 2.2.4 on 2019-09-09 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diploma_12', models.DecimalField(decimal_places=2, max_digits=5)),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('placed', models.BooleanField(default=False)),
                ('primary_mobile', models.CharField(max_length=10)),
                ('secondary_mobile', models.CharField(blank=True, max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('primary_mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('secondary_mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=50)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
