# Generated by Django 2.2.4 on 2019-09-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.CharField(choices=[('COMP', 'Computer Engineering'), ('IT', 'Information Engineering'), ('E&TC', 'E&TC Engineering'), ('PROD', 'Production Engineering'), ('INSTRU', 'Instrumentation Engineering'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], default='COMP', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='college_name',
            field=models.CharField(choices=[('DYPCOE', 'DYPCOE'), ('DYPIEMR', 'DYPIEMR')], default='DYPCOE', max_length=20),
        ),
    ]
