# Generated by Django 2.2.4 on 2019-09-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
