# Generated by Django 2.0.5 on 2019-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avg_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pnr',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='_id',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=2),
        ),
    ]
