# Generated by Django 2.0.5 on 2019-08-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190812_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pnr',
            new_name='id',
        ),
    ]
