# Generated by Django 2.2.4 on 2019-09-14 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_student_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
    ]
