# Generated by Django 2.0.5 on 2019-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190825_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
