# Generated by Django 2.2.4 on 2019-09-10 10:34

import djongo.models.fields
from django.db import migrations, models

import drive.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('rounds',
                 djongo.models.fields.EmbeddedModelField(model_container=drive.models.Drive_Rounds, null=True)),
                ('login_key', models.CharField(max_length=15)),
                ('eligibility',
                 djongo.models.fields.EmbeddedModelField(model_container=drive.models.Eligibility, null=True)),
                ('base_package', models.DecimalField(decimal_places=3, default='00', max_digits=8)),
                ('campus_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drive_Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_1', models.CharField(default='Aptitude Round', max_length=20)),
                ('round_2', models.CharField(default='Technical Round', max_length=20)),
                ('round_3', models.CharField(default='Interview Round', max_length=20)),
                ('round_4', models.CharField(default='HR Round', max_length=20)),
                ('round_5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marks', models.DecimalField(decimal_places=3, max_digits=5)),
                ('diploma_12', models.DecimalField(decimal_places=3, max_digits=5)),
                ('engg', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
