# Generated by Django 2.0.5 on 2019-10-07 14:44

import djongo.models.fields
from django.db import migrations, models

import drive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('_id', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=15)),
                ('venue', models.CharField(max_length=100)),
                ('campus_type', models.CharField(choices=[('On', 'On'), ('Off', 'Off'), ('Pool', 'Pool')], default='On', max_length=10)),
                ('Computer', models.BooleanField(default=False)),
                ('Civil', models.BooleanField(default=False)),
                ('Mechanical', models.BooleanField(default=False)),
                ('IT', models.BooleanField(default=False)),
                ('Instrumentation', models.BooleanField(default=False)),
                ('Production', models.BooleanField(default=False)),
                ('ENTC', models.BooleanField(default=False)),
                ('base_package', models.DecimalField(decimal_places=3, max_digits=8)),
                ('login_key', models.CharField(max_length=15)),
                ('rounds', djongo.models.fields.ArrayModelField(model_container=drive.models.Drive_Rounds)),
                ('eligibility', djongo.models.fields.ArrayModelField(model_container=drive.models.Eligibility)),
                ('eligible_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round1_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round2_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round3_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round4_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round5_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round6_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round7_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('round8_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
                ('placed_student', djongo.models.fields.ArrayModelField(model_container=drive.models.Attendance)),
            ],
        ),
    ]
