# Generated by Django 2.0.5 on 2019-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='branch',
        ),
        migrations.AddField(
            model_name='drive',
            name='Civil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='Computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='ENTC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='IT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='Instrumentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='Mechanical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drive',
            name='Production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drive',
            name='campus_type',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off'), ('Pool', 'Pool')], default='On', max_length=10),
        ),
    ]
