# Generated by Django 2.2.4 on 2019-09-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibility',
            old_name='engg',
            new_name='enggineering',
        ),
    ]
